<?php
$data = array (
  684 => 
  array (
    'cat_id' => '684',
    'cat_name' => '植物大战',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '684',
    'name' => '植物大战',
  ),
  685 => 
  array (
    'cat_id' => '685',
    'cat_name' => '小僵尸',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '685',
    'name' => '小僵尸',
  ),
  686 => 
  array (
    'cat_id' => '686',
    'cat_name' => '大僵尸',
    'measure_unit' => '',
    'parent_id' => '684',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '686',
    'name' => '大僵尸',
  ),
  688 => 
  array (
    'cat_id' => '688',
    'cat_name' => '最新产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '688',
    'name' => '最新产品',
  ),
  683 => 
  array (
    'cat_id' => '683',
    'cat_name' => '电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '1',
    'level' => 0,
    'id' => '683',
    'name' => '电器',
  ),
  687 => 
  array (
    'cat_id' => '687',
    'cat_name' => '小电器',
    'measure_unit' => '',
    'parent_id' => '683',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '687',
    'name' => '小电器',
  ),
);
?>